### ISSUE TITLE
Transfer Effects is not Working at all

### ISSUE THREAD

**Issue by ItsSnib** [hexle-at/ItemEffects#11]
Server version: paper 1.19.3
Plugin version: laterst (1.2.0)

so... when i try to use the /transfer command, nothing happens, i tried many times but nothing's working
in the console the error looks like this:

[21:25:55 WARN]: [ItemEffects] Task #9040 for ItemEffects v1.2.0 generated an exception
java.lang.ClassCastException: class net.minecraft.nbt.NBTTagCompound cannot be cast to class java.util.Set (net.minecraft.nbt.NBTTagCompound is in unnamed module of loader java.net.URLClassLoader @7aec35a; java.util.Set is in module java.base of loader 'bootstrap')
        at at.hexle.nbtapi.NBTReflectionUtil.getKeys(NBTReflectionUtil.java:588) ~[Item_Effects-v1_2_0.jar:?]
        at at.hexle.nbtapi.NBTCompound.getKeys(NBTCompound.java:542) ~[Item_Effects-v1_2_0.jar:?]
        at at.hexle.main.NBTHandler.readEffectsADD(NBTHandler.java:87) ~[Item_Effects-v1_2_0.jar:?]
        at at.hexle.main.Effects.updateMainHand(Effects.java:132) ~[Item_Effects-v1_2_0.jar:?]
        at at.hexle.events.Events.lambda$onPlayerCommand$0(Events.java:56) ~[Item_Effects-v1_2_0.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-386]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:440) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-386]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[21:26:04 ERROR]: Could not pass event InventoryCloseEvent to ItemEffects v1.2.0
java.lang.ClassCastException: class net.minecraft.nbt.NBTTagCompound cannot be cast to class java.util.Set (net.minecraft.nbt.NBTTagCompound is in unnamed module of loader java.net.URLClassLoader @7aec35a; java.util.Set is in module java.base of loader 'bootstrap')
        at at.hexle.nbtapi.NBTReflectionUtil.getKeys(NBTReflectionUtil.java:588) ~[Item_Effects-v1_2_0.jar:?]
        at at.hexle.nbtapi.NBTCompound.getKeys(NBTCompound.java:542) ~[Item_Effects-v1_2_0.jar:?]
        at at.hexle.main.NBTHandler.readEffectsADD(NBTHandler.java:87) ~[Item_Effects-v1_2_0.jar:?]
        at at.hexle.main.Effects.updateMainHand(Effects.java:132) ~[Item_Effects-v1_2_0.jar:?]
        at at.hexle.events.Events.onInvClose(Events.java:141) ~[Item_Effects-v1_2_0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor44.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-386]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1543) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:2923) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:2916) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClosePacket.handle(ServerboundContainerClosePacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClosePacket.a(ServerboundContainerClosePacket.java:10) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-386]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

i don't really know what to do, so... i hope it can be fixed soon, thank you for reading

**Comment by hexle-at** [comment]
Hello, thanks for reporting the bug. Tomorrow there will be a new version, we will have a look onto the bug in the next hours and try to fix the error!

Thanks for providing all the information, that really speeds up the bug-solving-process!

**Comment by Pianist20005** [comment]
Hello @ItsSnib, we have good news, the problem could be solved, a new version has been released and can be downloaded on the spigot page. There has been a lot of testing and all tests have passed successfully.
Please let us know if the problem has also been fixed on your server.  Thanks in advance!
