### ISSUE TITLE
 ItemEffects Plugin and Mythicmobs conflict issue

### ISSUE THREAD

**Issue by binqidada** [hexle-at/ItemEffects#6]
Contents:
Server-Version: Paper-1.12.2
Plugin-Version: 1.1.0

Error: when I use it, it is not compatible with the mythicmobs item, and when a player falls into the void, there is a swipe screen when it falls into the void, and mm errors are reported,My my mythmobs version is 4.11.0, and I'll submit an error message later。

**Comment by hexle-at** [comment]
Hello, thanks for reporting this bug! We will have a closer look onto this bug. As soon as we have any further information we will inform you!

**Comment by binqidada** [comment]
[16:32:09 WARN]: AsyncLogger error handling event seq=913, value='':
[16:32:09 WARN]: java.lang.NullPointerException
[16:32:09 WARN]:        at org.apache.logging.log4j.core.async.RingBufferLogEvent.execute(RingBufferLogEvent.java:161)
[16:32:09 WARN]:        at org.apache.logging.log4j.core.async.RingBufferLogEventHandler.onEvent(RingBufferLogEventHandler.java:45)
[16:32:09 WARN]:        at org.apache.logging.log4j.core.async.RingBufferLogEventHandler.onEvent(RingBufferLogEventHandler.java:29)
[16:32:09 WARN]:        at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168)
[16:32:09 WARN]:        at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125)
[16:32:09 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[16:32:09 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[16:32:09 WARN]:        at java.lang.Thread.run(Thread.java:748)

**Comment by binqidada** [comment]
[16:34:58 ERROR]: [MythicMobs] [EVENTS] Exception thrown whilst handling event: org.bukkit.event.inventory.InventoryCloseEvent
[16:34:58 ERROR]: Could not pass event InventoryCloseEvent to MythicMobs v4.11.0-da8c22c1
java.lang.StackOverflowError: null
        at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:156) ~[?:1.8.0_281]
        at org.apache.logging.log4j.io.ByteStreamLogger$ByteBufferInputStream.read(ByteStreamLogger.java:54) ~[Paper.jar:git-Paper-1618]
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284) ~[?:1.8.0_281]
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326) ~[?:1.8.0_281]
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178) ~[?:1.8.0_281]
        at java.io.InputStreamReader.read(InputStreamReader.java:184) ~[?:1.8.0_281]
        at java.io.Reader.read(Reader.java:140) ~[?:1.8.0_281]
        at org.apache.logging.log4j.io.ByteStreamLogger.extractMessages(ByteStreamLogger.java:91) ~[Paper.jar:git-Paper-1618]
        at org.apache.logging.log4j.io.ByteStreamLogger.put(ByteStreamLogger.java:137) ~[Paper.jar:git-Paper-1618]
        at org.apache.logging.log4j.io.LoggerOutputStream.write(LoggerOutputStream.java:65) ~[Paper.jar:git-Paper-1618]
        at java.io.PrintStream.write(PrintStream.java:480) ~[?:1.8.0_281]
        at org.apache.logging.log4j.io.LoggerPrintStream.write(LoggerPrintStream.java:224) ~[Paper.jar:git-Paper-1618]
        at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221) ~[?:1.8.0_281]
        at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291) ~[?:1.8.0_281]
        at sun.nio.cs.StreamEncoder.flushBuffer(StreamEncoder.java:104) ~[?:1.8.0_281]
        at java.io.OutputStreamWriter.flushBuffer(OutputStreamWriter.java:185) ~[?:1.8.0_281]
        at java.io.PrintStream.write(PrintStream.java:527) ~[?:1.8.0_281]
        at java.io.PrintStream.print(PrintStream.java:669) ~[?:1.8.0_281]
        at org.apache.logging.log4j.io.LoggerPrintStream.print(LoggerPrintStream.java:147) ~[Paper.jar:git-Paper-1618]
        at java.io.PrintStream.println(PrintStream.java:823) ~[?:1.8.0_281]
        at org.apache.logging.log4j.io.LoggerPrintStream.println(LoggerPrintStream.java:204) ~[Paper.jar:git-Paper-1618]
        at java.lang.Throwable$WrappedPrintStream.println(Throwable.java:749) ~[?:1.8.0_281]
        at java.lang.Throwable.printStackTrace(Throwable.java:656) ~[?:1.8.0_281]
        at java.lang.Throwable.printStackTrace(Throwable.java:644) ~[?:1.8.0_281]
        at java.lang.Throwable.printStackTrace(Throwable.java:635) ~[?:1.8.0_281]
        at io.lumine.xikage.mythicmobs.utils.events.functional.SubscriptionBuilder.lambda$static$0(SubscriptionBuilder.java:19) ~[?:?]
        at io.lumine.xikage.mythicmobs.utils.events.functional.single.EventListener.execute(EventListener.java:137) ~[?:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[Paper.jar:git-Paper-1618]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Paper.jar:git-Paper-1618]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[Paper.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:982) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.EntityPlayer.closeInventory(EntityPlayer.java:999) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.EntityPlayer.die(EntityPlayer.java:501) ~[Paper.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:106) ~[Paper.jar:git-Paper-1618]
        at at.hexle.main.Effects.updateArmor(Effects.java:60) ~[?:?]
        at at.hexle.events.Events.onInvClose(Events.java:116) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor4.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[Paper.jar:git-Paper-1618]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[Paper.jar:git-Paper-1618]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Paper.jar:git-Paper-1618]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[Paper.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:982) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.EntityPlayer.closeInventory(EntityPlayer.java:999) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.EntityPlayer.die(EntityPlayer.java:501) ~[Paper.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:106) ~[Paper.jar:git-Paper-1618]
        at at.hexle.main.Effects.updateArmor(Effects.java:60) ~[?:?]
        at at.hexle.events.Events.onInvClose(Events.java:116) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor4.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[Paper.jar:git-Paper-1618]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[Paper.jar:git-Paper-1618]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Paper.jar:git-Paper-1618]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[Paper.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:982) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.EntityPlayer.closeInventory(EntityPlayer.java:999) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.EntityPlayer.die(EntityPlayer.java:501) ~[Paper.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:106) ~[Paper.jar:git-Paper-1618]

**Comment by hexle-at** [comment]
Thanks for the errors!

I've just tried to reproduce the error, but there was no error whilst trying it.
Here is what I've done:
1. /mythicmobs items get BanditTunic
2. /itemeffects add glowing 1 hide (-> INFO: visible effects do NOT work, this is cancelled by MythicMobs I think)
3A. throw the item into the void
3B. jump into the void (I died)
3C. Put the BanditTunic on (this is a chestplate) whilst 3A and 3B
3D. Hold it in my hand whilst 3A and 3B

But everything looked good.
-> May you explain, how to reproduce the error?
If you have created a "new" item, that is not included when the plugin is downloaded, you can send us your "items" order from the Mythic plugin via email [developer@hexle.at](mailto:developer@hexle.at) or attach it right in here, so we can test your items and figure out the problem.

**Comment by binqidada** [comment]
I may understand that it was because I used the Backpack Editor to edit it twice after generating mm gear, and then triggered the problem, but some of the mechanisms of itemefects made it impossible for him and mm to judge the error caused by the void

**Comment by binqidada** [comment]
After further testing, it was not my backpack editor, but the problem of not being able to destroy this property

**Comment by hexle-at** [comment]
Okay, so the error caused by the void is still not resolved?

**Comment by binqidada** [comment]
Sorry, it may be that I have a strange conflict with some other plugins on my side, and then lead to the addition of the ItemEffects plugin, if there is no way to destroy this property, falling into the void will cause this problem

**Comment by hexle-at** [comment]
Okay this is strange, which other plugins do you have on your server?
Did this error occure in an older version of the ItemEffects plugin? (Or isn't it working since the latest update?)

**Comment by binqidada** [comment]
I started using it at 1.0.9, but when I tested it, I accidentally found that there was a problem of falling into the void

**Comment by binqidada** [comment]
Is there a possibility of NBT conflict？There is a possibility of NBT conflict, I am troubleshooting plugins that may appear in a little bit？emmm...

**Comment by hexle-at** [comment]
I don't think that the problem occures because of the NBT:
1. We have stored all NBT information in a special NBTCompound: "IE_HEXLE"
2. If any other plugin would delete this NBTCompound, the effects just would not work
3. The chance that another plugin modifies our NBTCompound is very very unlikely

Is the second error (the long one) that you have sent, the error that appears when you fall into the void?
